proxy:
  port: 80
  container-wait-time: 30000
  heartbeat-timeout: 600000
  container-log-path: /opt/shinyproxy/log/
  authentication: none
  admin-groups: admins
  docker:
      internal-networking: true
  specs:
  - id: omicsBroker
    description: omicsBroker
    container-cmd: ["R", "-e", "omicsBroker::shiny_application(port = 3838, host = '0.0.0.0')"]
    container-image: tdenecker/omicsbroker
    container-network: sp-network
logging:
  file:
    shinyproxy.log