project <- fluidPage(

  fluidRow(h1("Project"),
           fluidRow(
             column(6,
                    h3("General"),

                    tags$label(class="control-label", "Title", tags$span(style="color:red;", "*")),
                    helpText(style="font-style: italic;", "A title project"),
                    textInput("projectSet_title", label = NULL, width = "100%"),

                    tags$label(class="control-label", "Alias", tags$span(style="color:red;", "*")),
                    helpText(style="font-style: italic;", "An alias to the project (i.e.: salivarius_dynamic)"),
                    textInput("projectSet_alias", label = NULL, width = "100%"),


                    tags$label(class="control-label", "Description", tags$span(style="color:red;", "*")),
                    helpText(style="font-style: italic;", "An alias to the project (i.e.: salivarius_dynamic)"),
                    textAreaInput("projectSet_description", label = NULL, width = "100%",
                                  resize = "vertical"),

                    h2("Team"),
                    div(style="width:300px",
                        textInput("projectSet_description", label = "Submitter user name", width = "100%") %>%
                          helper(type = "inline",
                                 title = "Submitter user name",
                                 content = c("This is a <b>text input</b>.",
                                             "This is on a new line."))
                    ),

                    dateInput("release_date", "Release date"),

                    h2("Organization"),
                    textInput("Organization_name", label = "Organization name"),
                    selectInput("Organization_role",label = "Organization role",  choices = "owner"),
                    selectInput("Organization_type", label = "Organization type", choices = "center"),

                    h2("Contact"),
                    textInput("Contact_email", label = "Contact email"),
                    textInput("Contact_First", label = "Contact first name"),
                    textInput("Contact_Last", label = "Contact last name")

             ),

             column(6,
                    h3("Manifest file"),
                    fluidRow(
                      column(6,
                             tags$label(class="control-label", "STUDY"),
                             helpText(style="font-style: italic;",
                                      "Study accession or unique name (alias)"),
                             textInput("mf_STUDY", label = NULL),

                             tags$label(class="control-label", "SAMPLE"),
                             helpText(style="font-style: italic;",
                                      "Sample accession or unique name (alias)"),
                             textInput("mf_SAMPLE", label = NULL),

                             tags$label(class="control-label", "NAME"),
                             helpText(style="font-style: italic;",
                                      "Unique experiment name"),
                             textInput("mf_NAME", label = NULL),

                             tags$label(class="control-label", "PLATFORM"),
                             helpText(style="font-style: italic;",
                                      "Not needed if INSTRUMENT is provided."),
                             selectInput("mf_PLATFORM",label = NULL,
                                         choices = c("LS454", "ILLUMINA","PACBIO_SMRT",
                                                     "ION_TORRENT","CAPILLARY",
                                                     "OXFORD_NANOPORE","BGISEQ","DNBSEQ")),

                             tags$label(class="control-label", "INSTRUMENT"),
                             helpText(style="font-style: italic;",
                                      "Lorem"),
                             selectInput("mf_INSTRUMENT",label = NULL,
                                         choices = c("454 GS",
                                                     "454 GS 20",
                                                     "454 GS FLX",
                                                     "454 GS FLX+",
                                                     "454 GS FLX Titanium",
                                                     "454 GS Junior",
                                                     "HiSeq X Five",
                                                     "HiSeq X Ten",
                                                     "Illumina Genome Analyzer",
                                                     "Illumina Genome Analyzer II",
                                                     "Illumina Genome Analyzer IIx",
                                                     "Illumina HiScanSQ",
                                                     "Illumina HiSeq 1000",
                                                     "Illumina HiSeq 1500",
                                                     "Illumina HiSeq 2000",
                                                     "Illumina HiSeq 2500",
                                                     "Illumina HiSeq 3000",
                                                     "Illumina HiSeq 4000",
                                                     "Illumina iSeq 100",
                                                     "Illumina MiSeq",
                                                     "Illumina MiniSeq",
                                                     "Illumina NovaSeq 6000",
                                                     "NextSeq 500",
                                                     "NextSeq 550",
                                                     "PacBio RS",
                                                     "PacBio RS II",
                                                     "Sequel",
                                                     "Ion Torrent PGM",
                                                     "Ion Torrent Proton",
                                                     "Ion Torrent S5",
                                                     "Ion Torrent S5 XL",
                                                     "AB 3730xL Genetic Analyzer",
                                                     "AB 3730 Genetic Analyzer",
                                                     "AB 3500xL Genetic Analyzer",
                                                     "AB 3500 Genetic Analyzer",
                                                     "AB 3130xL Genetic Analyzer",
                                                     "AB 3130 Genetic Analyzer",
                                                     "AB 310 Genetic Analyzer",
                                                     "MinION",
                                                     "GridION",
                                                     "PromethION",
                                                     "BGISEQ-500",
                                                     "DNBSEQ-T7",
                                                     "DNBSEQ-G400",
                                                     "DNBSEQ-G50",
                                                     "DNBSEQ-G400 FAST",
                                                     "unspecified")),

                             tags$label(class="control-label", "INSERT_SIZE"),
                             helpText(style="font-style: italic;",
                                      "Insert size for paired reads"),
                             numericInput("mf_INSERT_SIZE",label = NULL, 200)
                      ),
                      column(6,
                             tags$label(class="control-label", "LIBRARY NAME"),
                             helpText(style="font-style: italic;",
                                      "Library name (optional)"),
                             textInput("mf_LIBRARY_NAME", label = NULL),

                             tags$label(class="control-label", "LIBRARY SOURCE"),
                             helpText(style="font-style: italic;",
                                      "Lorem"),
                             selectInput("mf_LIBRARY_SOURCE",label = NULL,
                                         choices = c("GENOMIC","GENOMIC SINGLE CELL",
                                                     "TRANSCRIPTOMIC","TRANSCRIPTOMIC SINGLE CELL",
                                                     "METAGENOMIC","METATRANSCRIPTOMIC",
                                                     "SYNTHETIC","VIRAL RNA","OTHER")),

                             tags$label(class="control-label", "LIBRARY SELECTION"),
                             helpText(style="font-style: italic;",
                                      "Lorem"),
                             selectInput("mf_LIBRARY_SELECTION",label = NULL,
                                         choices = c("RANDOM",
                                                     "PCR",
                                                     "RANDOM PCR",
                                                     "RT-PCR",
                                                     "HMPR",
                                                     "MF",
                                                     "repeat fractionation",
                                                     "size fractionation",
                                                     "MSLL",
                                                     "cDNA",
                                                     "cDNA_randomPriming",
                                                     "cDNA_oligo_dT",
                                                     "PolyA",
                                                     "Oligo-dT",
                                                     "Inverse rRNA",
                                                     "Inverse rRNA selection",
                                                     "ChIP",
                                                     "ChIP-Seq",
                                                     "MNase",
                                                     "DNase",
                                                     "Hybrid Selection",
                                                     "Reduced Representation",
                                                     "Restriction Digest",
                                                     "5-methylcytidine antibody",
                                                     "MBD2 protein methyl-CpG binding domain",
                                                     "CAGE",
                                                     "RACE",
                                                     "MDA",
                                                     "padlock probes capture method",
                                                     "other",
                                                     "unspecified")
                             ),

                             tags$label(class="control-label", "LIBRARY STRATEGY"),
                             helpText(style="font-style: italic;",
                                      "Lorem"),
                             selectInput("mf_LIBRARY_STRATEGY",label = NULL,
                                         choices = c("WGS",
                                                     "WGA",
                                                     "WXS",
                                                     "RNA-Seq",
                                                     "ssRNA-seq",
                                                     "miRNA-Seq",
                                                     "ncRNA-Seq",
                                                     "FL-cDNA",
                                                     "EST",
                                                     "Hi-C",
                                                     "ATAC-seq",
                                                     "WCS",
                                                     "RAD-Seq",
                                                     "CLONE",
                                                     "POOLCLONE",
                                                     "AMPLICON",
                                                     "CLONEEND",
                                                     "FINISHING",
                                                     "ChIP-Seq",
                                                     "MNase-Seq",
                                                     "DNase-Hypersensitivity",
                                                     "Bisulfite-Seq",
                                                     "CTS",
                                                     "MRE-Seq",
                                                     "MeDIP-Seq",
                                                     "MBD-Seq",
                                                     "Tn-Seq",
                                                     "VALIDATION",
                                                     "FAIRE-seq",
                                                     "SELEX",
                                                     "RIP-Seq",
                                                     "ChIA-PET",
                                                     "Synthetic-Long-Read",
                                                     "Targeted-Capture",
                                                     "Tethered Chromatin Conformation Capture",
                                                     "OTHER")
                             ),

                             tags$label(class="control-label", "DESCRIPTION"),
                             helpText(style="font-style: italic;",
                                      "free text library description (optional)"),
                             textAreaInput("mf_DESCRIPTION", label = NULL),

                             tags$label(class="control-label", "FILE TYPE"),
                             helpText(style="font-style: italic;",
                                      "Lorem"),
                             selectInput("mf_LIBRARY_STRATEGY",label = NULL,
                                         choices = c("BAM","CRAM", "FASTQ")
                             )
                      )
                    )
             )
           )
  )
)
